lang_strings = {
    "en": {
        "title": " Photography Toolbox",
        "title_short": " Photo Tools",
        "home": "Home",
        "dof": "Depth of Field",
        "priority": "Priority",
        "priority_modes": "Priority modes",
        "exposure": "Exposure",
        "flash_exposure": "Flash exposure",
        "aov": "Angles of view",
        "settings": "Settings",
        "f_stop": "F-stop",
        "distance": "Distance",
        "guide_number": "Guide number",
        "coc": "Circle of Confusion",
        "focal_length": "Focal length",
        "enlargement": "Enlargement",
        "sensor": "Sensor format",
        "hyperfocal": "Hyperfocal dist",
        "near_limit": "Near limit",
        "far_limit": "Far limit",
        "shutter": "Shutter",
        "result": "result",
        "EV": "EV"
    },
    "de": {
        "title": " Photographie-Toolbox",
        "title_short": " Photo-Tools",
        "home": "Startseite",
        "dof": "Tiefenschärfe",
        "priority": "Vorwahl",
        "priority_modes": "Halbautomatiken",
        "exposure": "Belichtung",
        "flash_exposure": "Belichtung (Blitz)",
        "aov": "Bildwinkel",
        "settings": "Einstellungen",
        "f_stop": "Blende",
        "distance": "Entfernung",
        "guide_number": "Leitzahl",
        "coc": "Zerstreuung",
        "focal_length": "Brennweite",
        "enlargement": "Vergrößerung",
        "sensor": "Sensorformat",
        "hyperfocal": "Hyperfokale",
        "near_limit": "Nahgrenze",
        "far_limit": "Ferngrenze",
        "shutter": "Verschlusszeit",
        "result": "Ergebnis",
        "EV": "LW"
    }
}