lang_strings = {
    "en": {
        "title": " Photography Toolbox",
        "title_short": " Photo Tools",
        "index": "Home",
        "av_tv": "Priority modes",
        "dof": "Depth of Field",
        "priority": "Priority",
        "priority_modes": "Priority modes",
        "exposure": "Exposure",
        "flash_exposure": "Flash exposure",
        "flash": "Flash exposure",
        "aov": "Angles of view",
        "settings": "Settings",
        "f_stop": "F-stop",
        "distance": "Distance",
        "guide_number": "Guide number",
        "coc": "Circle of Confusion",
        "focal_length": "Focal length",
        "enlargement": "Enlargement",
        "sensor": "Sensor format",
        "hyperfocal": "Hyperfocal dist",
        "near_limit": "Near limit",
        "far_limit": "Far limit",
        "shutter": "Shutter",
        "result": "result",
        "EV": "EV",
        "original_settings": "Original settings:",
        "target_settings": "Target settings:",
        "calculate": "Calculate:",
        "equiv_exposure": "Equivalent exposure",
        "equiv_focal_length": "Equivalent focal length",
        "lpmm": "line pairs / mm",
        "view_distance": "View distance",
        "use_custom_coc": "Use custom Circle of Confusion calculation"
    },
    "de": {
        "title": " Photographie-Toolbox",
        "title_short": " Photo-Tools",
        "index": "Startseite",
        "av_tv": "Halbautomatiken",
        "dof": "Tiefenschärfe",
        "priority": "Vorwahl",
        "priority_modes": "Halbautomatiken",
        "exposure": "Belichtung",
        "flash_exposure": "Belichtung (Blitz)",
        "flash": "Belichtung (Blitz)",
        "aov": "Bildwinkel",
        "settings": "Einstellungen",
        "f_stop": "Blende",
        "distance": "Entfernung",
        "guide_number": "Leitzahl",
        "coc": "Zerstreuung",
        "focal_length": "Brennweite",
        "enlargement": "Vergrößerung",
        "sensor": "Sensorformat",
        "hyperfocal": "Hyperfokale",
        "near_limit": "Nahgrenze",
        "far_limit": "Ferngrenze",
        "shutter": "Verschlusszeit",
        "result": "Ergebnis",
        "EV": "LW",
        "original_settings": "Ursprüngl. Einstellungen:",
        "target_settings": "Zieleinstellungen:",
        "calculate": "Berechnen:",
        "equiv_exposure": "Äquivalente Belichtung",
        "equiv_focal_length": "Äquivalente Brennweite",
        "lpmm": "Linienpaare/mm",
        "view_distance": "Bildabstand",
        "use_custom_coc": "Zerstreuungskreis berechnen"
    }
}